-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 15:44:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_futbol
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_futbol` ;

-- -----------------------------------------------------
-- Schema db_futbol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_futbol` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_futbol` ;

-- -----------------------------------------------------
-- Table `db_futbol`.`posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_futbol`.`posicion` (
  `id_posicion` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('ARQUERO', 'DEFENSA', 'MEDIOCAMPISTA', 'DELANTERO', 'EXTREMO') NULL DEFAULT NULL,
  PRIMARY KEY (`id_posicion`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_futbol`.`futbolista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_futbol`.`futbolista` (
  `id_futbolista` BIGINT NOT NULL AUTO_INCREMENT,
  `caracteristicas` VARCHAR(255) NULL DEFAULT NULL,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_nacido` DATE NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `id_posicion` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_futbolista`),
  CONSTRAINT `FKowp5qw331irknf4prsc3m0m6x`
    FOREIGN KEY (`id_posicion`)
    REFERENCES `db_futbol`.`posicion` (`id_posicion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKowp5qw331irknf4prsc3m0m6x` ON `db_futbol`.`futbolista` (`id_posicion` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -- Registros-------
INSERT INTO futbolista (Nombres, Apellidos, fecha_nacido, id_posicion, caracteristicas)
VALUES
  ('Lionel', 'Messi', '1987-06-24', 4, 'Habilidoso, excelente regate y visión de juego'),
  ('Cristiano', 'Ronaldo', '1985-02-05', 4, 'Poderoso remate, gran capacidad física'),
  ('Neymar', 'Junior', '1992-02-05', 5, 'Hábil driblador, creativo en el ataque'),
  ('Kylian', 'Mbappé', '1998-12-20', 5, 'Rápido, habilidoso y goleador'),
  ('Robert', 'Lewandowski', '1988-08-21', 4, 'Instinto goleador, potente remate'),
  ('Kevin', 'De Bruyne', '1991-06-28', 3, 'Excelente visión de juego, buen pasador'),
  ('Virgil', 'van Dijk', '1991-07-08', 2, 'Sólido en defensa, gran juego aéreo'),
  ('Sergio', 'Ramos', '1986-03-30', 2, 'Líder en defensa, goleador en jugadas de estrategia'),
  ('Luis', 'Suárez', '1987-01-24', 4, 'Oportuno en el área, excelente definidor'),
  ('Mohamed', 'Salah', '1992-06-15', 5, 'Rápido, habilidoso en el regate'),
  ('Manuel', 'Neuer', '1986-03-27', 1, 'Excelentes reflejos, habilidad con los pies'),
  ('Joshua', 'Kimmich', '1995-02-08', 3, 'Polivalente, buen pasador y recuperador'),
  ('Sadio', 'Mané', '1992-04-10', 5, 'Rápido, habilidoso en el uno contra uno'),
  ('Toni', 'Kroos', '1990-01-04', 3, 'Preciso en el pase, visión de juego'),
  ('Romelu', 'Lukaku', '1993-05-13', 4, 'Potente, habilidoso en el área'),
  ('Jan', 'Oblak', '1993-01-07', 1, 'Seguro bajo los palos, buen juego con los pies'),
  ('Bruno', 'Fernandes', '1994-09-08', 3, 'Creador de juego, buen lanzador de faltas'),
  ('Karim', 'Benzema', '1987-12-19', 4, 'Técnico, habilidoso, buen definidor'),
  ('Eden', 'Hazard', '1991-01-07', 5, 'Habilidoso, rápido, buen regate'),
  ('Marc-André', 'ter Stegen', '1992-04-30', 1, 'Ágil, buen juego de pies'),
  ('Raheem', 'Sterling', '1994-12-08', 5, 'Rápido, habilidoso en el regate'),
  ('Mohamed', 'Sissoko', '1994-01-22', 3, 'Físico, buen recuperador de balón'),
  ('João', 'Félix', '1999-11-10', 4, 'Técnico, habilidoso, buen definidor'),
  ('Thomas', 'Müller', '1989-09-13', 3, 'Inteligente, buen pasador, llegador'),
  ('Andrew', 'Robertson', '1994-03-11', 2, 'Rápido, buen centrador, sólido en defensa');

